### ISSUE TITLE
Using with dokku

### ISSUE THREAD

**Issue by nonunknown** [GodotNuts/GodotServer-Docker#4]
In my use case I'm using "manual-export" and [dokku](https://dokku.com/) as the PaaS, and it doesnt support `docker_compose`
so how can I convert the docker_compose's commands to a way dokku supports? 

```
version: '3'

services:
  godot:
    build: .
    ports:
      - "12345:12345"
      - "12345:12345/udp"
    tty: true
    container_name: godot-server
```

at least open the ports, something like that!
